### ISSUE TITLE
Kirki 4 incompatibility

### ISSUE THREAD

**Issue by mapsteps** [codelessteam/codeless-page-builder#1]
It seems like Codeless builder & the themes that are using it are not compatible with the latest version of Kirki.

https://github.com/kirki-framework/kirki/issues/2421

**Comment by ludjon** [comment]
We will update our plugin in the next days, thank you for the notification!

**Comment by mapsteps** [comment]
Beautiful, thank you! :)

**Comment by mapsteps** [comment]
Any update on this? We have re-released Kirki yesterday and people keep reporting issues with Codeless. https://github.com/kirki-framework/kirki/issues/2451

**Comment by ludjon** [comment]
Yes, I am almost ready on publishing the new version of plugin. I have an issue with ColorSwatches to use the new react-colorful element. How can I define color swatches?

**Comment by mapsteps** [comment]
Okay, great :)

Are you referring to those default/predefined colors?

![grafik](https://user-images.githubusercontent.com/22119831/152984519-1c564685-83df-4b63-b2d9-b99184d186fe.png)

**Comment by ludjon** [comment]
I found the solution. We load the controls in a dynamic way for our codeless page builder.

**Comment by ludjon** [comment]
We just uploaded a new version of our Codeless Page Builder plugin (v1.1.0).

Thank You!
